class card{
    constructor(layer,x,y,type,level){
        this.layer=layer
        this.position={x:x,y:y}
        this.type=type
        this.level=level
        this.name=types.card[this.type].name
        this.damage=types.card[this.type].stats[this.level].damage
        this.cost=types.card[this.type].stats[this.level].cost
        this.attack=types.card[this.type].stats[this.level].attack
        this.target=types.card[this.type].stats[this.level].target
        this.desc=types.card[this.type].stats[this.level].desc
        this.spec=types.card[this.type].stats[this.level].spec
        this.anim={select:0,afford:0}
        this.width=120
        this.height=160
        this.size=0
        this.fade=1
        this.calcDirection=0
        this.remove=false
        this.discard=false
        this.select=false
        this.trigger=false
        this.used=false
    }
    display(){
        if(this.size>0){
            this.layer.translate(this.position.x,this.position.y)
            this.layer.scale(this.size)
            this.layer.fill(255,this.fade*this.anim.select)
            this.layer.noStroke()
            this.layer.rect(0,0,this.width+15,this.height+15,10)
            if(this.spec!=1){
                this.layer.fill(200,160,200,this.fade)
                this.layer.stroke(160,120,160,this.fade)
                this.layer.strokeWeight(5)
                this.layer.rect(0,0,this.width,this.height,5)
                this.layer.fill(200,225,250,this.fade)
                this.layer.stroke(150,200,250,this.fade)
                this.layer.strokeWeight(3)
                this.layer.quad(-this.width/2+4,-this.height/2+20,-this.width/2+16,-this.height/2+4,-this.width/2+28,-this.height/2+20,-this.width/2+16,-this.height/2+36)
            }else{
                this.layer.fill(120,this.fade)
                this.layer.stroke(80,this.fade)
                this.layer.strokeWeight(5)
                this.layer.rect(0,0,this.width,this.height,5)
            }
            this.layer.fill(this.anim.afford*240,0,0,this.fade)
            this.layer.noStroke()
            if(this.spec!=1){
                this.layer.textSize(20)
                this.layer.text(this.cost,-this.width/2+16,-this.height/2+20)
            }
            this.layer.fill(0,this.fade)
            this.layer.textSize(16)
            this.layer.text(this.name,0,-this.height/2+20)
            this.layer.textSize(12)
            this.layer.text(this.desc,0,10)
            this.layer.scale(1/this.size)
            this.layer.translate(-this.position.x,-this.position.y)
        }
    }
    update(mana){
        if(this.size<1&&!this.used){
            this.size=round(this.size*5+1)*0.2
        }else if(this.size>0&&this.used){
            this.size=round(this.size*5-1)*0.2
        }
        if(this.size<=0&&this.used){
            this.discard=true
        }
        if(this.select&&this.anim.select<1){
            this.anim.select=round(this.anim.select*5+1)/5
        }else if(!this.select&&this.anim.select>0){
            this.anim.select=round(this.anim.select*5-1)/5
        }
        if(mana.main<this.cost&&this.anim.afford<1){
            this.anim.afford=round(this.anim.afford*5+1)/5
        }else if(mana.main>=this.cost&&this.anim.afford>0){
            this.anim.afford=round(this.anim.afford*5-1)/5
        }
        if(this.trigger&&!this.used){
            if(dist(this.position.x,this.position.y,100,120)<20){
                this.position.x=100
                this.position.y=120
            }else{
                this.calcDirection=atan2(100-this.position.x,120-this.position.y)
                this.position.x+=sin(this.calcDirection)*20
                this.position.y+=cos(this.calcDirection)*20
            }
        }
    }
}