types={
    card:[
        {name:'',rarity:0,list:-1,
        stats:[
            {damage:0,alt:0,cost:0,attack:0,target:0,desc:'',spec:0,class:0},
            {damage:0,alt:0,cost:0,attack:0,target:0,desc:'',spec:0,class:0},
        ],
        },{name:'Strike',rarity:0,list:5,
        stats:[
            {damage:6,alt:0,cost:1,attack:1,target:1,desc:'',spec:0,class:0},
            {damage:9,alt:0,cost:1,attack:1,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Defend',rarity:0,list:5,
        stats:[
            {damage:5,alt:0,cost:1,attack:2,target:0,desc:'',spec:0,class:1},
            {damage:8,alt:0,cost:1,attack:2,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Big Strike',rarity:0,list:1,
        stats:[
            {damage:14,alt:0,cost:2,attack:1,target:1,desc:'',spec:0,class:0},
            {damage:22,alt:0,cost:2,attack:1,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Triple',rarity:0,list:1,
        stats:[
            {damage:3,alt:3,cost:1,attack:3,target:1,desc:'',spec:0,class:0},
            {damage:4,alt:3,cost:1,attack:3,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Think',rarity:0,list:1,
        stats:[
            {damage:2,alt:0,cost:1,attack:4,target:0,desc:'',spec:0,class:2},
            {damage:2,alt:0,cost:0,attack:4,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Weaken',rarity:0,list:1,
        stats:[
            {damage:2,alt:0,cost:0,attack:5,target:1,desc:'',spec:0,class:2},
            {damage:3,alt:0,cost:0,attack:5,target:1,desc:'',spec:0,class:2},
        ],
        },{name:'Electrify',rarity:1,list:1,
        stats:[
            {damage:2,alt:3,cost:1,attack:6,target:0,desc:'',spec:0,class:1},
            {damage:4,alt:6,cost:1,attack:6,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Dynamic\nShield',rarity:0,list:1,
        stats:[
            {damage:4,alt:0,cost:-1,attack:7,target:0,desc:'',spec:0,class:1},
            {damage:6,alt:0,cost:-1,attack:7,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Limit\nBreak',rarity:1,list:1,
        stats:[
            {damage:12,alt:0,cost:0,attack:8,target:1,desc:'',spec:0,class:0},
            {damage:18,alt:0,cost:0,attack:8,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Exhausting\nStrike',rarity:0,list:1,
        stats:[
            {damage:9,alt:0,cost:0,attack:9,target:1,desc:'',spec:0,class:0},
            {damage:12,alt:0,cost:0,attack:9,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Chain\nStrike',rarity:0,list:1,
        stats:[
            {damage:5,alt:0,cost:1,attack:10,target:1,desc:'',spec:0,class:0},
            {damage:7,alt:0,cost:0,attack:10,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Hook\nStrike',rarity:1,list:1,
        stats:[
            {damage:4,alt:1,cost:1,attack:11,target:1,desc:'',spec:0,class:0},
            {damage:6,alt:1,cost:1,attack:11,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Multi\nStrike',rarity:0,list:1,
        stats:[
            {damage:6,alt:0,cost:2,attack:12,target:0,desc:'',spec:0,class:0},
            {damage:9,alt:0,cost:2,attack:12,target:0,desc:'',spec:0,class:0},
        ],
        },{name:'Head\nSmash',rarity:2,list:1,
        stats:[
            {damage:30,alt:0,cost:3,attack:18,target:1,desc:'',spec:0,class:0},
            {damage:48,alt:0,cost:3,attack:18,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Charge\nStrike',rarity:1,list:1,
        stats:[
            {damage:5,alt:0,cost:-1,attack:23,target:1,desc:'',spec:0,class:0},
            {damage:7,alt:0,cost:-1,attack:23,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Melt',rarity:1,list:1,
        stats:[
            {damage:10,alt:0,cost:1,attack:32,target:1,desc:'',spec:0,class:0},
            {damage:14,alt:0,cost:1,attack:32,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Nerve\nStrike',rarity:0,list:1,
        stats:[
            {damage:2,alt:3,cost:1,attack:34,target:1,desc:'',spec:0,class:0},
            {damage:4,alt:3,cost:1,attack:34,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Jolt',rarity:0,list:1,
        stats:[
            {damage:2,alt:0,cost:0,attack:35,target:0,desc:'',spec:0,class:0},
            {damage:4,alt:0,cost:0,attack:35,target:0,desc:'',spec:0,class:0},
        ],
        },{name:'Combo\nFinish',rarity:0,list:1,
        stats:[
            {damage:14,alt:2,cost:4,attack:36,target:1,desc:'',spec:4,class:0},
            {damage:22,alt:2,cost:4,attack:36,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Hammer\nFist',rarity:0,list:1,
        stats:[
            {damage:7,alt:1,cost:1,attack:37,target:1,desc:'',spec:0,class:0},
            {damage:10,alt:1,cost:1,attack:37,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Strengthen',rarity:0,list:1,
        stats:[
            {damage:1,alt:0,cost:1,attack:38,target:0,desc:'',spec:0,class:2},
            {damage:2,alt:0,cost:1,attack:38,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Counter',rarity:0,list:1,
        stats:[
            {damage:4,alt:5,cost:1,attack:39,target:0,desc:'',spec:0,class:1},
            {damage:7,alt:6,cost:1,attack:39,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Combo\nCounter',rarity:1,list:1,
        stats:[
            {damage:3,alt:2,cost:1,attack:40,target:0,desc:'',spec:0,class:1},
            {damage:5,alt:6,cost:1,attack:40,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Combo\nStrike',rarity:0,list:1,
        stats:[
            {damage:9,alt:0,cost:3,attack:1,target:1,desc:'',spec:4,class:0},
            {damage:14,alt:0,cost:3,attack:1,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Virtuous\nCircle',rarity:1,list:1,
        stats:[
            {damage:7,alt:0,cost:5,attack:35,target:0,desc:'',spec:4,class:2},
            {damage:9,alt:0,cost:5,attack:35,target:0,desc:'',spec:4,class:2},
        ],
        },{name:'Palm\nStrike',rarity:0,list:1,
        stats:[
            {damage:8,alt:2,cost:4,attack:41,target:1,desc:'',spec:4,class:0},
            {damage:10,alt:3,cost:4,attack:41,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Heavy\nOverhand',rarity:2,list:1,
        stats:[
            {damage:28,alt:0,cost:10,attack:1,target:1,desc:'',spec:4,class:0},
            {damage:44,alt:0,cost:10,attack:1,target:1,desc:'',spec:4,class:0},
        ], 
        },{name:'Throw',rarity:0,list:1,
        stats:[
            {damage:2,alt:1,cost:1,attack:42,target:1,desc:'',spec:0,class:0},
            {damage:6,alt:1,cost:1,attack:42,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Stomp',rarity:1,list:1,
        stats:[
            {damage:4,alt:12,cost:1,attack:43,target:1,desc:'',spec:0,class:0},
            {damage:5,alt:20,cost:1,attack:43,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Unleash',rarity:2,list:1,
        stats:[
            {damage:1,alt:3,cost:2,attack:44,target:1,desc:'',spec:0,class:0},
            {damage:3,alt:3,cost:2,attack:44,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Jumping\nBack Kick',rarity:2,list:1,
        stats:[
            {damage:14,alt:0,cost:5,attack:45,target:1,desc:'',spec:4,class:0},
            {damage:26,alt:0,cost:5,attack:45,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Left\nSpin Kick',rarity:1,list:1,
        stats:[
            {damage:11,alt:6,cost:3,attack:46,target:1,desc:'',spec:4,class:0},
            {damage:18,alt:10,cost:3,attack:46,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Right\nSpin Kick',rarity:1,list:1,
        stats:[
            {damage:11,alt:6,cost:3,attack:47,target:1,desc:'',spec:4,class:0},
            {damage:18,alt:10,cost:3,attack:47,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Brutal\nKick',rarity:0,list:1,
        stats:[
            {damage:24,alt:2,cost:4,attack:48,target:1,desc:'',spec:0,class:0},
            {damage:34,alt:3,cost:4,attack:48,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Jumping\nGround Punch',rarity:2,list:1,
        stats:[
            {damage:8,alt:28,cost:6,attack:43,target:1,desc:'',spec:4,class:0},
            {damage:12,alt:40,cost:6,attack:43,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Link',rarity:1,list:1,
        stats:[
            {damage:3,alt:0,cost:2,attack:4,target:0,desc:'',spec:4,class:0},
            {damage:3,alt:0,cost:2,attack:4,target:0,desc:'',spec:4,class:0},
        ],
        },{name:'Shock',rarity:1,list:1,
        stats:[
            {damage:1,alt:8,cost:1,attack:49,target:0,desc:'',spec:0,class:0},
            {damage:3,alt:12,cost:1,attack:49,target:0,desc:'',spec:0,class:0},
        ],
        },{name:'540 Kick',rarity:2,list:1,
        stats:[
            {damage:8,alt:2,cost:2,attack:50,target:1,desc:'',spec:0,class:0},
            {damage:12,alt:2,cost:2,attack:50,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Surprise\nCounter',rarity:1,list:1,
        stats:[
            {damage:2,alt:15,cost:4,attack:39,target:0,desc:'',spec:4,class:1},
            {damage:6,alt:22,cost:4,attack:39,target:0,desc:'',spec:4,class:1},
        ],
        },{name:'Stagger',rarity:1,list:1,
        stats:[
            {damage:15,alt:1,cost:5,attack:42,target:1,desc:'',spec:4,class:0},
            {damage:15,alt:1,cost:4,attack:42,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Pressure\nPoint',rarity:1,list:1,
        stats:[
            {damage:15,alt:0,cost:4,attack:54,target:1,desc:'',spec:4,class:0},
            {damage:23,alt:0,cost:4,attack:54,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Defensive\nPosition',rarity:1,list:1,
        stats:[
            {damage:4,alt:0,cost:1,attack:92,target:0,desc:'',spec:0,class:1},
            {damage:6,alt:0,cost:1,attack:92,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Shove',rarity:1,list:1,
        stats:[
            {damage:6,alt:12,cost:5,attack:93,target:1,desc:'',spec:4,class:0},
            {damage:6,alt:12,cost:4,attack:93,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Power\nSink',rarity:1,list:1,
        stats:[
            {damage:4,alt:0,cost:1,attack:94,target:0,desc:'',spec:0,class:1},
            {damage:7,alt:0,cost:1,attack:94,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Option\nPlay',rarity:0,list:1,
        stats:[
            {damage:5,alt:6,cost:1,attack:63,target:1,desc:'',spec:0,class:0},
            {damage:8,alt:9,cost:1,attack:63,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Vigilance',rarity:1,list:2,
        stats:[
            {damage:8,alt:0,cost:2,attack:27,target:0,desc:'',spec:0,class:1},
            {damage:12,alt:0,cost:2,attack:27,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Eruption',rarity:1,list:2,
        stats:[
            {damage:9,alt:0,cost:2,attack:95,target:1,desc:'',spec:0,class:1},
            {damage:9,alt:0,cost:1,attack:95,target:1,desc:'',spec:0,class:1},
        ],
        },{name:'Cycle\nStrike',rarity:1,list:2,
        stats:[
            {damage:12,alt:0,cost:2,attack:24,target:1,desc:'',spec:0,class:0},
            {damage:18,alt:0,cost:2,attack:24,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Sweep',rarity:0,list:2,
        stats:[
            {damage:4,alt:2,cost:1,attack:51,target:1,desc:'',spec:2,class:0},
            {damage:6,alt:2,cost:1,attack:51,target:1,desc:'',spec:2,class:0},
        ],
        },{name:'Spinning\nWhack',rarity:1,list:2,
        stats:[
            {damage:12,alt:4,cost:2,attack:52,target:1,desc:'',spec:5,class:0},
            {damage:20,alt:4,cost:2,attack:52,target:1,desc:'',spec:5,class:0},
        ],
        },{name:'Shiv',rarity:0,list:2,
        stats:[
            {damage:4,alt:0,cost:0,attack:1,target:1,desc:'',spec:3,class:0},
            {damage:6,alt:0,cost:0,attack:1,target:1,desc:'',spec:3,class:0},
        ],
        },{name:'Blade\nDance',rarity:2,list:2,
        stats:[
            {damage:3,alt:0,cost:1,attack:26,target:0,desc:'',spec:0,class:2},
            {damage:4,alt:0,cost:1,attack:26,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Empty\nBody',rarity:0,list:2,
        stats:[
            {damage:7,alt:0,cost:1,attack:28,target:0,desc:'',spec:0,class:1},
            {damage:10,alt:0,cost:1,attack:28,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'No Fear',rarity:1,list:2,
        stats:[
            {damage:8,alt:0,cost:1,attack:29,target:1,desc:'',spec:0,class:0},
            {damage:11,alt:0,cost:1,attack:29,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Empty\nBlade',rarity:0,list:2,
        stats:[
            {damage:9,alt:0,cost:1,attack:30,target:1,desc:'',spec:0,class:0},
            {damage:14,alt:0,cost:1,attack:30,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Empty\nMind',rarity:1,list:2,
        stats:[
            {damage:2,alt:0,cost:1,attack:31,target:0,desc:'',spec:0,class:2},
            {damage:3,alt:0,cost:1,attack:31,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Charge',rarity:0,list:3,
        stats:[
            {damage:1,alt:0,cost:0,attack:13,target:0,desc:'',spec:0,class:2},
            {damage:2,alt:0,cost:0,attack:13,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Multicast',rarity:0,list:3,
        stats:[
            {damage:2,alt:0,cost:1,attack:14,target:0,desc:'',spec:0,class:2},
            {damage:3,alt:0,cost:1,attack:14,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Detonate',rarity:1,list:3,
        stats:[
            {damage:1,alt:0,cost:1,attack:15,target:0,desc:'',spec:0,class:2},
            {damage:1,alt:0,cost:0,attack:15,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Shielding',rarity:0,list:3,
        stats:[
            {damage:1,alt:0,cost:0,attack:16,target:0,desc:'',spec:0,class:2},
            {damage:2,alt:0,cost:0,attack:16,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Expel',rarity:1,list:3,
        stats:[
            {damage:0,alt:0,cost:2,attack:17,target:0,desc:'',spec:0,class:2},
            {damage:0,alt:0,cost:1,attack:17,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Streamline',rarity:1,list:3,
        stats:[
            {damage:1,alt:0,cost:1,attack:19,target:0,desc:'',spec:0,class:2},
            {damage:2,alt:0,cost:0,attack:19,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Energize',rarity:1,list:3,
        stats:[
            {damage:1,alt:0,cost:2,attack:20,target:0,desc:'',spec:0,class:2},
            {damage:1,alt:0,cost:1,attack:20,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Beam\nPulse',rarity:0,list:3,
        stats:[
            {damage:3,alt:1,cost:0,attack:21,target:1,desc:'',spec:0,class:0},
            {damage:4,alt:2,cost:0,attack:21,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Claw',rarity:0,list:3,
        stats:[
            {damage:3,alt:0,cost:0,attack:22,target:1,desc:'',spec:0,class:0},
            {damage:5,alt:0,cost:0,attack:22,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Flash',rarity:2,list:4,
        stats:[
            {damage:1,alt:1,cost:3,attack:64,target:0,desc:'',spec:3,class:2},
            {damage:2,alt:2,cost:3,attack:64,target:0,desc:'',spec:3,class:2},
        ],
        },{name:'Danger',rarity:0,list:4,
        stats:[
            {damage:8,alt:-4,cost:1,attack:65,target:1,desc:'',spec:0,class:0},
            {damage:12,alt:-4,cost:1,attack:65,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Peace',rarity:0,list:4,
        stats:[
            {damage:7,alt:4,cost:1,attack:66,target:0,desc:'',spec:0,class:1},
            {damage:11,alt:4,cost:1,attack:66,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Outburst',rarity:1,list:4,
        stats:[
            {damage:1,alt:0,cost:1,attack:67,target:1,desc:'',spec:0,class:0},
            {damage:1,alt:0,cost:0,attack:67,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Inburst',rarity:1,list:4,
        stats:[
            {damage:1,alt:0,cost:1,attack:68,target:0,desc:'',spec:0,class:1},
            {damage:1,alt:0,cost:0,attack:68,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Revert',rarity:0,list:4,
        stats:[
            {damage:0,alt:0,cost:0,attack:69,target:0,desc:'',spec:0,class:2},
            {damage:0,alt:0,cost:0,attack:69,target:0,desc:'',spec:2,class:2},
        ],
        },{name:'Serenity',rarity:0,list:4,
        stats:[
            {damage:2,alt:2,cost:0,attack:70,target:0,desc:'',spec:0,class:1},
            {damage:3,alt:2,cost:0,attack:70,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Windslash',rarity:0,list:4,
        stats:[
            {damage:8,alt:-2,cost:2,attack:71,target:0,desc:'',spec:11,class:0},
            {damage:13,alt:-2,cost:2,attack:71,target:0,desc:'',spec:11,class:0},
        ],
        },{name:'Petal\nCloud',rarity:1,list:4,
        stats:[
            {damage:4,alt:6,cost:1,attack:72,target:1,desc:'',spec:0,class:0},
            {damage:12,alt:6,cost:1,attack:72,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Throw',rarity:0,list:4,
        stats:[
            {damage:24,alt:0,cost:1,attack:73,target:1,desc:'',spec:11,class:0},
            {damage:40,alt:0,cost:1,attack:73,target:1,desc:'',spec:11,class:0},
        ],
        },{name:'Collect',rarity:0,list:4,
        stats:[
            {damage:0,alt:0,cost:0,attack:74,target:0,desc:'',spec:0,class:2},
            {damage:0,alt:0,cost:0,attack:74,target:0,desc:'',spec:2,class:2},
        ],
        },{name:'Parry',rarity:0,list:4,
        stats:[
            {damage:1,alt:-3,cost:1,attack:75,target:0,desc:'',spec:11,class:1},  
            {damage:2,alt:-3,cost:1,attack:75,target:0,desc:'',spec:11,class:1},
        ],
        },{name:'Slash',rarity:0,list:4,
        stats:[
            {damage:5,alt:-6,cost:1,attack:76,target:1,desc:'',spec:11,class:0},
            {damage:7,alt:-6,cost:1,attack:76,target:1,desc:'',spec:11,class:0},
        ],
        },{name:'Decisive\nStab',rarity:2,list:4,
        stats:[
            {damage:16,alt:-12,cost:2,attack:77,target:1,desc:'',spec:11,class:0},
            {damage:25,alt:-12,cost:2,attack:77,target:1,desc:'',spec:11,class:0},
        ],
        },{name:'Flurry',rarity:1,list:4,
        stats:[
            {damage:2,alt:-5,cost:1,attack:78,target:1,desc:'',spec:0,class:0},
            {damage:3,alt:-5,cost:1,attack:78,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Complete',rarity:2,list:4,
        stats:[
            {damage:1,alt:0,cost:2,attack:79,target:0,desc:'',spec:3,class:2},
            {damage:1,alt:0,cost:1,attack:79,target:0,desc:'',spec:3,class:2},
        ],
        },{name:'Evanes\ncence',rarity:1,list:4,
        stats:[
            {damage:1,alt:5,cost:1,attack:80,target:0,desc:'',spec:0,class:1},
            {damage:1,alt:5,cost:1,attack:80,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Silence',rarity:1,list:4,
        stats:[
            {damage:0,alt:-3,cost:0,attack:81,target:1,desc:'',spec:3,class:1},
            {damage:0,alt:-3,cost:0,attack:81,target:1,desc:'',spec:0,class:1},
        ],
        },{name:'Power\nWithin',rarity:1,list:4,
        stats:[
            {damage:2,alt:2,cost:2,attack:82,target:0,desc:'',spec:3,class:1},
            {damage:2,alt:2,cost:2,attack:82,target:0,desc:'',spec:3,class:1},
        ],
        },{name:'Guard',rarity:0,list:4,
        stats:[
            {damage:15,alt:1,cost:2,attack:66,target:0,desc:'',spec:12,class:1},
            {damage:22,alt:1,cost:2,attack:66,target:0,desc:'',spec:12,class:1},
        ],
        },{name:'Slice',rarity:2,list:4,
        stats:[
            {damage:12,alt:0,cost:2,attack:83,target:0,desc:'',spec:11,class:0},
            {damage:20,alt:0,cost:2,attack:83,target:0,desc:'',spec:11,class:0},
        ],
        },{name:'Footwork',rarity:0,list:4,
        stats:[
            {damage:1,alt:1,cost:1,attack:84,target:0,desc:'',spec:0,class:1},
            {damage:2,alt:1,cost:1,attack:84,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Caltrops',rarity:1,list:4,
        stats:[
            {damage:4,alt:-3,cost:2,attack:85,target:0,desc:'',spec:0,class:2},
            {damage:6,alt:-3,cost:2,attack:85,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Slide',rarity:0,list:4,
        stats:[
            {damage:4,alt:0,cost:1,attack:86,target:1,desc:'',spec:0,class:0},
            {damage:8,alt:0,cost:1,attack:86,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Swivel',rarity:0,list:4,
        stats:[
            {damage:3,alt:0,cost:1,attack:87,target:0,desc:'',spec:0,class:1},
            {damage:7,alt:0,cost:1,attack:87,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Diversion',rarity:1,list:4,
        stats:[
            {damage:21,alt:0,cost:1,attack:88,target:0,desc:'',spec:11,class:1},
            {damage:35,alt:0,cost:1,attack:88,target:0,desc:'',spec:11,class:1},
        ],
        },{name:'Luminosity',rarity:2,list:4,
        stats:[
            {damage:4,alt:12,cost:2,attack:89,target:0,desc:'',spec:0,class:2},
            {damage:6,alt:12,cost:2,attack:89,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Parasol',rarity:1,list:4,
        stats:[
            {damage:3,alt:1,cost:0,attack:90,target:1,desc:'',spec:2,class:0},
            {damage:5,alt:1,cost:0,attack:90,target:1,desc:'',spec:2,class:0},
        ],
        },{name:'Sleeve\nSwipe',rarity:0,list:4,
        stats:[
            {damage:4,alt:-1,cost:1,attack:91,target:1,desc:'',spec:10,class:0},
            {damage:4,alt:-1,cost:0,attack:91,target:1,desc:'',spec:10,class:0},
        ],
        },{name:'Heal Up',rarity:1,list:0,
        stats:[
            {damage:4,alt:0,cost:1,attack:25,target:0,desc:'',spec:3,class:2},
            {damage:6,alt:0,cost:1,attack:25,target:0,desc:'',spec:3,class:2},
        ],
        },{name:'Breath',rarity:1,list:0,
        stats:[
            {damage:1,alt:0,cost:0,attack:55,target:0,desc:'',spec:0,class:2},
            {damage:2,alt:0,cost:0,attack:55,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Entrance',rarity:1,list:0,
        stats:[
            {damage:8,alt:0,cost:0,attack:12,target:0,desc:'',spec:8,class:1},
            {damage:12,alt:0,cost:0,attack:12,target:0,desc:'',spec:8,class:1},
        ],
        },{name:'Enlighten',rarity:1,list:0,
        stats:[
            {damage:1,alt:0,cost:0,attack:53,target:0,desc:'',spec:0,class:2},
            {damage:1,alt:0,cost:0,attack:53,target:0,desc:'',spec:2,class:2},
        ],
        },{name:'Purity',rarity:1,list:0,
        stats:[
            {damage:0,alt:0,cost:0,attack:56,target:0,desc:'',spec:3,class:0},
            {damage:0,alt:0,cost:0,attack:56,target:0,desc:'',spec:9,class:0},
        ],
        },{name:'Finesse',rarity:1,list:0,
        stats:[
            {damage:2,alt:1,cost:0,attack:57,target:0,desc:'',spec:0,class:1},
            {damage:4,alt:1,cost:0,attack:57,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Apotheosis',rarity:2,list:0,
        stats:[
            {damage:0,alt:0,cost:2,attack:58,target:0,desc:'',spec:3,class:2},
            {damage:0,alt:0,cost:1,attack:58,target:0,desc:'',spec:3,class:2},
        ],
        },{name:'Metamor\nphosis',rarity:2,list:0,
        stats:[
            {damage:3,alt:0,cost:2,attack:59,target:0,desc:'',spec:3,class:2},
            {damage:5,alt:0,cost:2,attack:59,target:0,desc:'',spec:3,class:2},
        ],
        },{name:'Strategist',rarity:2,list:0,
        stats:[
            {damage:3,alt:0,cost:0,attack:4,target:0,desc:'',spec:0,class:2},
            {damage:4,alt:0,cost:0,attack:4,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Hand of\nGreed',rarity:0,list:0,
        stats:[
            {damage:20,alt:20,cost:2,attack:60,target:1,desc:'',spec:0,class:0},
            {damage:25,alt:25,cost:2,attack:60,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Chrysalis',rarity:2,list:0,
        stats:[
            {damage:3,alt:0,cost:2,attack:61,target:0,desc:'',spec:3,class:2},
            {damage:5,alt:0,cost:2,attack:61,target:0,desc:'',spec:3,class:2},
        ],
        },{name:'Mind Blast',rarity:0,list:0,
        stats:[
            {damage:6,alt:0,cost:2,attack:62,target:1,desc:'',spec:10,class:0},
            {damage:9,alt:0,cost:1,attack:62,target:1,desc:'',spec:2,class:0},
        ],
        },{name:'Clumsy',rarity:-1,list:10,
        stats:[
            {damage:0,alt:0,cost:0,attack:-3,target:0,desc:'',spec:6,class:0},
            {damage:0,alt:0,cost:0,attack:-3,target:0,desc:'',spec:6,class:0},
        ],
        },{name:'Doubt',rarity:-1,list:10,
        stats:[
            {damage:0,alt:0,cost:0,attack:-4,target:0,desc:'',spec:1,class:0},
            {damage:0,alt:0,cost:0,attack:-4,target:0,desc:'',spec:1,class:0},
        ],
        },{name:'Regret',rarity:-1,list:10,
        stats:[
            {damage:0,alt:0,cost:0,attack:-5,target:0,desc:'',spec:1,class:0},
            {damage:0,alt:0,cost:0,attack:-5,target:0,desc:'',spec:1,class:0},
        ],
        },{name:'Writhe',rarity:-1,list:10,
        stats:[
            {damage:0,alt:0,cost:0,attack:-6,target:0,desc:'',spec:7,class:0},
            {damage:0,alt:0,cost:0,attack:-6,target:0,desc:'',spec:7,class:0},
        ],
        },{name:'Shame',rarity:-1,list:10,
        stats:[
            {damage:0,alt:0,cost:0,attack:-7,target:0,desc:'',spec:1,class:0},
            {damage:0,alt:0,cost:0,attack:-7,target:0,desc:'',spec:1,class:0},
        ],
        },{name:'Parasite',rarity:-1,list:10,
        stats:[
            {damage:0,alt:0,cost:0,attack:-8,target:0,desc:'',spec:1,class:0},
            {damage:0,alt:0,cost:0,attack:-8,target:0,desc:'',spec:1,class:0},
        ],
        },{name:'Confusion',rarity:-2,list:11,
        stats:[
            {damage:0,alt:0,cost:0,attack:-1,target:0,desc:'',spec:1,class:0},
            {damage:0,alt:0,cost:0,attack:-1,target:0,desc:'',spec:1,class:0},
        ],
        },{name:'Bleed',rarity:-2,list:11,
        stats:[
            {damage:0,alt:0,cost:0,attack:-2,target:0,desc:'',spec:1,class:0},
            {damage:0,alt:0,cost:0,attack:-2,target:0,desc:'',spec:1,class:0},
        ],
        },{name:'Dazed',rarity:-2,list:11,
        stats:[
            {damage:0,alt:0,cost:0,attack:-3,target:0,desc:'',spec:6,class:0},
            {damage:0,alt:0,cost:0,attack:-3,target:0,desc:'',spec:6,class:0},
        ],
        },{name:'Stuck',rarity:-2,list:11,
        stats:[
            {damage:0,alt:0,cost:1,attack:0,target:0,desc:'',spec:3,class:0},
            {damage:0,alt:0,cost:1,attack:0,target:0,desc:'',spec:3,class:0},
        ],
        },{name:'Void',rarity:-2,list:11,
        stats:[
            {damage:1,alt:0,cost:0,attack:-9,target:0,desc:'',spec:1,class:0},
            {damage:1,alt:0,cost:0,attack:-9,target:0,desc:'',spec:1,class:0},
        ],
        },{name:'Burn',rarity:-2,list:11,
        stats:[
            {damage:1,alt:0,cost:0,attack:-10,target:0,desc:'',spec:1,class:0},
            {damage:1,alt:0,cost:0,attack:-10,target:0,desc:'',spec:1,class:0},
        ],
        },
    ],combatant:[
        {name:'',alt:'',life:0,height:0,behavior:0,attacks:[],damage:[],altAttack:[],class:0},
        {name:'Agent',alt:'',life:80,height:75,behavior:0,attacks:[],damage:[],altAttack:[],class:0},
        {name:'Duelist',alt:'',life:50,height:75,behavior:0,attacks:[],damage:[],altAttack:[],class:0},
        {name:'Executor',alt:'',life:60,height:75,behavior:0,attacks:[],damage:[],altAttack:[],class:0},
        {name:'Creation',alt:'',life:40,height:75,behavior:0,attacks:[],damage:[],altAttack:[],class:0},
        {name:'Human',alt:'',life:20,height:75,behavior:0,attacks:[1,1,2],damage:[4,4,4],altAttack:[],class:0},
    ],attack:[
        {class:0},
        {class:0},
        {class:1},
    ],encounter:[
        {
            combatants:[0,0,0,0,0,0],
            reinforce:[],
            threshold:0,
            objective:[],
        },{
            combatants:[5,0,0,0,0,0],
            reinforce:[],
            threshold:2,
            objective:[[0,10,0,0],[1,5,2,20]],
        },{
            combatants:[5,5,5,0,0,0],
            reinforce:[5],
            threshold:3,
            objective:[[0,10,1,0],[1,5,3,10]],
        },
    ],event:[
        {
            name:'Dropped Book',
            pages:[
                {
                    desc:"You come across what appears to be a book lying in the dirt.\n"+
                    "Peering into it, you see numerous Konaian writings on the art of combat.\n\n"+
                    "When you pick it up, you notice the its extreme length and the poor condition of its pages.\n"+
                    "And there seems to be some sort of energy radiating from it...",
                    option:['Read','Leave'],
                    optionDesc:['Lose 4 Health',''],
                    link:[1,2],
                },{
                    desc:"The book is extremely long and quite confusing, but manages to keep you interested.\n"+
                    "After several hours, you finally reach the end. You've learned some, but you feel weakened.",
                    option:['Exit'],
                    optionDesc:['Gain 1 Card'],
                    link:[-1],
                },{
                    desc:"You leave, knowing it isn't worth the risk.",
                    option:['Exit'],
                    optionDesc:[''],
                    link:[-1],
                },
            ],
        },
    ],
}
listing={
    card:[[],[],[],[],[],[],[],[],[],[],[],[]],
}
zones=[
    {
        encounters:[1],
        elites:[2],
        events:[1],
    },
]
stage={scale:0,scene:'battle'}
graphics={main:0,minor:[]}
transition={trigger:false,anim:0,scene:stage.scene}
inputs={mouse:{x:0,y:0},rel:{x:0,y:0},keys:[[false,false,false,false],[false,false,false,false]]}
a=0;b=0;c=0;d=0;e=0;f=0;g=0;h=0;i=0;j=0;k=0;l=0;m=0;n=0;o=0;p=0
la=0;lb=0;lc=0;ld=0;le=0;lf=0;lg=0;lh=0;li=0;lj=0;lk=0;ll=0;lm=0;ln=0;lo=0;lp=0