types={
    card:[
        {name:'',
        stats:[],
        },{name:'Strike',rarity:0,
        stats:[
            {damage:6,alt:0,cost:1,attack:1,target:1,desc:'',spec:0,class:0},
            {damage:9,alt:0,cost:1,attack:1,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Defend',rarity:0,
        stats:[
            {damage:5,alt:0,cost:1,attack:2,target:0,desc:'',spec:0,class:1},
            {damage:8,alt:0,cost:1,attack:2,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Big Strike',rarity:0,
        stats:[
            {damage:14,alt:0,cost:2,attack:1,target:1,desc:'',spec:0,class:0},
            {damage:22,alt:0,cost:2,attack:1,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Triple',rarity:1,
        stats:[
            {damage:3,alt:3,cost:1,attack:3,target:1,desc:'',spec:0,class:0},
            {damage:4,alt:3,cost:1,attack:3,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Think',rarity:0,
        stats:[
            {damage:2,alt:0,cost:1,attack:4,target:0,desc:'',spec:0,class:3},
            {damage:2,alt:0,cost:0,attack:4,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Confusion',rarity:-1,
        stats:[
            {damage:0,alt:0,cost:0,attack:0,target:0,desc:'',spec:1,class:0},
            {damage:0,alt:0,cost:0,attack:0,target:0,desc:'',spec:1,class:0},
        ],
        },{name:'Weaken',rarity:0,
        stats:[
            {damage:2,alt:0,cost:0,attack:5,target:1,desc:'',spec:0,class:2},
            {damage:3,alt:0,cost:0,attack:5,target:1,desc:'',spec:0,class:2},
        ],
        },{name:'Electrify',rarity:1,
        stats:[
            {damage:2,alt:3,cost:1,attack:6,target:0,desc:'',spec:0,class:1},
            {damage:4,alt:6,cost:1,attack:6,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Dynamic\nShield',rarity:0,
        stats:[
            {damage:4,alt:0,cost:-1,attack:7,target:0,desc:'',spec:0,class:1},
            {damage:6,alt:0,cost:-1,attack:7,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Limit\nBreak',rarity:1,
        stats:[
            {damage:12,alt:0,cost:0,attack:8,target:1,desc:'',spec:0,class:0},
            {damage:18,alt:0,cost:0,attack:8,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Bleed',rarity:-1,
        stats:[
            {damage:0,alt:0,cost:0,attack:0,target:0,desc:'',spec:1,class:0},
            {damage:0,alt:0,cost:0,attack:0,target:0,desc:'',spec:1,class:0},
        ],
        },{name:'Exhausting\nStrike',rarity:0,
        stats:[
            {damage:9,alt:0,cost:0,attack:9,target:1,desc:'',spec:0,class:1},
            {damage:12,alt:0,cost:0,attack:9,target:1,desc:'',spec:0,class:1},
        ],
        },{name:'Chain\nStrike',rarity:0,
        stats:[
            {damage:5,alt:0,cost:1,attack:10,target:1,desc:'',spec:0,class:1},
            {damage:7,alt:0,cost:0,attack:10,target:1,desc:'',spec:0,class:1},
        ],
        },{name:'Hook\nStrike',rarity:1,
        stats:[
            {damage:4,alt:2,cost:1,attack:11,target:1,desc:'',spec:0,class:1},
            {damage:6,alt:2,cost:1,attack:11,target:1,desc:'',spec:0,class:1},
        ],
        },{name:'Multi\nStrike',rarity:0,
        stats:[
            {damage:6,alt:0,cost:2,attack:12,target:0,desc:'',spec:0,class:1},
            {damage:9,alt:0,cost:2,attack:12,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Charge',rarity:0,
        stats:[
            {damage:1,alt:0,cost:0,attack:13,target:0,desc:'',spec:0,class:3},
            {damage:2,alt:0,cost:0,attack:13,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Multicast',rarity:0,
        stats:[
            {damage:2,alt:0,cost:1,attack:14,target:0,desc:'',spec:0,class:2},
            {damage:3,alt:0,cost:1,attack:14,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Detonate',rarity:1,
        stats:[
            {damage:1,alt:0,cost:1,attack:15,target:0,desc:'',spec:0,class:3},
            {damage:1,alt:0,cost:0,attack:15,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Shielding',rarity:0,
        stats:[
            {damage:1,alt:0,cost:0,attack:16,target:0,desc:'',spec:0,class:3},
            {damage:2,alt:0,cost:0,attack:16,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Outburst',rarity:1,
        stats:[
            {damage:0,alt:0,cost:2,attack:17,target:0,desc:'',spec:0,class:2},
            {damage:0,alt:0,cost:1,attack:17,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Head\nSmash',rarity:2,
        stats:[
            {damage:30,alt:0,cost:3,attack:18,target:1,desc:'',spec:0,class:0},
            {damage:48,alt:0,cost:3,attack:18,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Streamline',rarity:1,
        stats:[
            {damage:1,alt:0,cost:1,attack:19,target:0,desc:'',spec:0,class:3},
            {damage:2,alt:0,cost:0,attack:19,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Energize',rarity:1,
        stats:[
            {damage:1,alt:0,cost:2,attack:20,target:0,desc:'',spec:0,class:3},
            {damage:1,alt:0,cost:1,attack:20,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Beam\nPulse',rarity:0,
        stats:[
            {damage:3,alt:1,cost:0,attack:21,target:1,desc:'',spec:0,class:0},
            {damage:4,alt:2,cost:0,attack:21,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Claw',rarity:0,
        stats:[
            {damage:3,alt:0,cost:0,attack:22,target:1,desc:'',spec:0,class:0},
            {damage:5,alt:0,cost:0,attack:22,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Charge\nStrike',rarity:1,
        stats:[
            {damage:5,alt:0,cost:-1,attack:23,target:1,desc:'',spec:0,class:0},
            {damage:7,alt:0,cost:-1,attack:23,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Cycle\nStrike',rarity:1,
        stats:[
            {damage:12,alt:0,cost:2,attack:24,target:1,desc:'',spec:0,class:0},
            {damage:18,alt:0,cost:2,attack:24,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Heal Up',rarity:1,
        stats:[
            {damage:4,alt:0,cost:1,attack:25,target:0,desc:'',spec:0,class:2},
            {damage:6,alt:0,cost:1,attack:25,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Sweep',rarity:0,
        stats:[
            {damage:4,alt:2,cost:1,attack:3,target:1,desc:'',spec:2,class:0},
            {damage:6,alt:2,cost:1,attack:3,target:1,desc:'',spec:2,class:0},
        ],
        },{name:'Spinning\nWhack',rarity:1,
        stats:[
            {damage:12,alt:4,cost:2,attack:1,target:1,desc:'',spec:2,class:0},
            {damage:20,alt:4,cost:2,attack:1,target:1,desc:'',spec:2,class:0},
        ],
        },{name:'Shiv',rarity:0,
        stats:[
            {damage:4,alt:0,cost:0,attack:1,target:1,desc:'',spec:3,class:0},
            {damage:6,alt:0,cost:0,attack:1,target:1,desc:'',spec:3,class:0},
        ],
        },{name:'Blade\nDance',rarity:2,
        stats:[
            {damage:3,alt:0,cost:1,attack:26,target:0,desc:'',spec:0,class:3},
            {damage:4,alt:0,cost:1,attack:26,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Vigilance',rarity:1,
        stats:[
            {damage:8,alt:0,cost:2,attack:27,target:0,desc:'',spec:0,class:1},
            {damage:12,alt:0,cost:2,attack:27,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Empty\nBody',rarity:0,
        stats:[
            {damage:7,alt:0,cost:1,attack:28,target:0,desc:'',spec:0,class:1},
            {damage:10,alt:0,cost:1,attack:28,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'No Fear',rarity:1,
        stats:[
            {damage:8,alt:0,cost:1,attack:29,target:1,desc:'',spec:0,class:0},
            {damage:11,alt:0,cost:1,attack:29,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Empty\nBlade',rarity:0,
        stats:[
            {damage:9,alt:0,cost:1,attack:30,target:1,desc:'',spec:0,class:0},
            {damage:14,alt:0,cost:1,attack:30,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Empty\nMind',rarity:1,
        stats:[
            {damage:2,alt:0,cost:1,attack:31,target:0,desc:'',spec:0,class:3},
            {damage:3,alt:0,cost:1,attack:31,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Melt',rarity:1,
        stats:[
            {damage:10,alt:0,cost:1,attack:32,target:1,desc:'',spec:0,class:0},
            {damage:14,alt:0,cost:1,attack:32,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Loop',rarity:1,
        stats:[
            {damage:1,alt:0,cost:1,attack:33,target:0,desc:'',spec:0,class:2},
            {damage:1,alt:0,cost:0,attack:33,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Disarm',rarity:0,
        stats:[
            {damage:2,alt:0,cost:1,attack:34,target:1,desc:'',spec:0,class:0},
            {damage:4,alt:0,cost:1,attack:34,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Jolt',rarity:0,
        stats:[
            {damage:2,alt:0,cost:0,attack:35,target:0,desc:'',spec:0,class:0},
            {damage:4,alt:0,cost:0,attack:35,target:0,desc:'',spec:0,class:0},
        ],
        },{name:'Combo\nFinish',rarity:1,
        stats:[
            {damage:14,alt:2,cost:4,attack:36,target:1,desc:'',spec:4,class:0},
            {damage:22,alt:2,cost:4,attack:36,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Hammer\nFist',rarity:0,
        stats:[
            {damage:7,alt:1,cost:1,attack:37,target:1,desc:'',spec:0,class:0},
            {damage:10,alt:1,cost:1,attack:37,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Strengthen',rarity:0,
        stats:[
            {damage:1,alt:0,cost:1,attack:38,target:0,desc:'',spec:0,class:3},
            {damage:2,alt:0,cost:1,attack:38,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Counter',rarity:0,
        stats:[
            {damage:4,alt:5,cost:1,attack:39,target:0,desc:'',spec:0,class:1},
            {damage:7,alt:6,cost:1,attack:39,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Combo\nCounter',rarity:1,
        stats:[
            {damage:3,alt:2,cost:1,attack:40,target:0,desc:'',spec:0,class:1},
            {damage:5,alt:6,cost:1,attack:40,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Combo\nStrike',rarity:0,
        stats:[
            {damage:9,alt:0,cost:2,attack:1,target:1,desc:'',spec:4,class:0},
            {damage:14,alt:0,cost:2,attack:1,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Virtuous\nCircle',rarity:1,
        stats:[
            {damage:7,alt:0,cost:5,attack:35,target:0,desc:'',spec:4,class:0},
            {damage:9,alt:0,cost:5,attack:35,target:0,desc:'',spec:4,class:0},
        ],
        },{name:'Palm\nStrike',rarity:1,
        stats:[
            {damage:8,alt:2,cost:4,attack:41,target:1,desc:'',spec:4,class:0},
            {damage:10,alt:3,cost:4,attack:41,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Heavy\nOverhand',rarity:2,
        stats:[
            {damage:28,alt:0,cost:10,attack:1,target:1,desc:'',spec:4,class:0},
            {damage:44,alt:0,cost:10,attack:1,target:1,desc:'',spec:4,class:0},
        ], 
        },{name:'Throw',rarity:1,
        stats:[
            {damage:2,alt:1,cost:1,attack:42,target:1,desc:'',spec:0,class:0},
            {damage:6,alt:1,cost:1,attack:42,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Stomp',rarity:1,
        stats:[
            {damage:4,alt:12,cost:1,attack:43,target:1,desc:'',spec:0,class:0},
            {damage:5,alt:20,cost:1,attack:43,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Unleash',rarity:2,
        stats:[
            {damage:1,alt:3,cost:2,attack:44,target:1,desc:'',spec:0,class:0},
            {damage:3,alt:3,cost:2,attack:44,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Jumping\nBack Kick',rarity:2,
        stats:[
            {damage:14,alt:0,cost:5,attack:45,target:1,desc:'',spec:4,class:0},
            {damage:26,alt:0,cost:5,attack:45,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Left\nSpin Kick',rarity:1,
        stats:[
            {damage:11,alt:6,cost:3,attack:46,target:1,desc:'',spec:4,class:0},
            {damage:18,alt:10,cost:3,attack:46,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Right\nSpin Kick',rarity:1,
        stats:[
            {damage:11,alt:6,cost:3,attack:47,target:1,desc:'',spec:4,class:0},
            {damage:18,alt:10,cost:3,attack:47,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Brutal\nKick',rarity:0,
        stats:[
            {damage:24,alt:2,cost:4,attack:48,target:1,desc:'',spec:0,class:0},
            {damage:34,alt:3,cost:4,attack:48,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Jumping\nGround Punch',rarity:2,
        stats:[
            {damage:8,alt:28,cost:6,attack:43,target:1,desc:'',spec:4,class:0},
            {damage:12,alt:40,cost:6,attack:43,target:1,desc:'',spec:4,class:0},
        ],
        },{name:'Link',rarity:1,
        stats:[
            {damage:3,alt:0,cost:2,attack:4,target:0,desc:'',spec:4,class:0},
            {damage:3,alt:0,cost:2,attack:4,target:0,desc:'',spec:4,class:0},
        ],
        },
    ],combatant:[
        {name:'',alt:'',life:0,height:0,behavior:0,attacks:[],damage:[],altAttack:[],class:0},
        {name:'Agent',alt:'',life:80,height:75,behavior:0,attacks:[],damage:[],altAttack:[],class:0},
        {name:'Player',alt:'',life:40,height:75,behavior:0,attacks:[],damage:[],altAttack:[],class:0},
        {name:'Executor',alt:'',life:60,height:75,behavior:0,attacks:[],damage:[],altAttack:[],class:0},
        {name:'Player',alt:'',life:40,height:75,behavior:0,attacks:[],damage:[],altAttack:[],class:0},
        {name:'Human',alt:'',life:20,height:75,behavior:0,attacks:[1,1,2],damage:[4,4,4],altAttack:[],class:0},
    ],attack:[
        {class:0},
        {class:0},
        {class:1},
    ]
}
combatants=[
    {type:5},
    {type:5},
    {type:5},
    {type:5},
    {type:5},
    {type:5},
]
stage={scale:0,scene:'battle'}
graphics={main:0,minor:[]}
transition={trigger:false,anim:0,scene:stage.scene}
inputs={mouse:{x:0,y:0},rel:{x:0,y:0},keys:[[false,false,false,false],[false,false,false,false]]}
a=0;b=0;c=0;d=0;e=0;f=0;g=0;h=0;i=0;j=0;k=0;l=0;m=0;n=0;o=0;p=0
la=0;lb=0;lc=0;ld=0;le=0;lf=0;lg=0;lh=0;li=0;lj=0;lk=0;ll=0;lm=0;ln=0;lo=0;lp=0