types={
    card:[
        {name:'',
        stats:[],
        },{name:'Strike',
        stats:[
            {damage:6,alt:0,cost:1,attack:1,target:1,desc:'',spec:0,class:0},
            {damage:9,alt:0,cost:1,attack:1,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Defend',
        stats:[
            {damage:5,alt:0,cost:1,attack:2,target:0,desc:'',spec:0,class:1},
            {damage:8,alt:0,cost:1,attack:2,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Big Strike',
        stats:[
            {damage:14,alt:0,cost:2,attack:1,target:1,desc:'',spec:0,class:0},
            {damage:22,alt:0,cost:2,attack:1,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Triple',
        stats:[
            {damage:3,alt:3,cost:1,attack:3,target:1,desc:'',spec:0,class:0},
            {damage:4,alt:3,cost:1,attack:3,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Think',
        stats:[
            {damage:2,alt:0,cost:1,attack:4,target:0,desc:'',spec:0,class:3},
            {damage:2,alt:0,cost:0,attack:4,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Confusion',
        stats:[
            {damage:0,alt:0,cost:0,attack:0,target:0,desc:'',spec:1,class:0},
            {damage:0,alt:0,cost:0,attack:0,target:0,desc:'',spec:1,class:0},
        ],
        },{name:'Weaken',
        stats:[
            {damage:2,alt:0,cost:0,attack:5,target:1,desc:'',spec:0,class:2},
            {damage:3,alt:0,cost:0,attack:5,target:1,desc:'',spec:0,class:2},
        ],
        },{name:'Electrify',
        stats:[
            {damage:3,alt:4,cost:1,attack:6,target:0,desc:'',spec:0,class:1},
            {damage:6,alt:8,cost:1,attack:6,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Dynamic\nShield',
        stats:[
            {damage:4,alt:0,cost:-1,attack:7,target:0,desc:'',spec:0,class:1},
            {damage:6,alt:0,cost:-1,attack:7,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Limit\nBreak',
        stats:[
            {damage:12,alt:0,cost:0,attack:8,target:1,desc:'',spec:0,class:0},
            {damage:18,alt:0,cost:0,attack:8,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Bleed',
        stats:[
            {damage:0,alt:0,cost:0,attack:0,target:0,desc:'',spec:1,class:0},
            {damage:0,alt:0,cost:0,attack:0,target:0,desc:'',spec:1,class:0},
        ],
        },{name:'Exhausting\nStrike',
        stats:[
            {damage:8,alt:0,cost:0,attack:9,target:1,desc:'',spec:0,class:1},
            {damage:12,alt:0,cost:0,attack:9,target:1,desc:'',spec:0,class:1},
        ],
        },{name:'Chain\nStrike',
        stats:[
            {damage:5,alt:0,cost:1,attack:10,target:1,desc:'',spec:0,class:1},
            {damage:7,alt:0,cost:0,attack:10,target:1,desc:'',spec:0,class:1},
        ],
        },{name:'Hook\nStrike',
        stats:[
            {damage:4,alt:2,cost:1,attack:11,target:1,desc:'',spec:0,class:1},
            {damage:6,alt:2,cost:1,attack:11,target:1,desc:'',spec:0,class:1},
        ],
        },{name:'Multi\nStrike',
        stats:[
            {damage:6,alt:0,cost:2,attack:12,target:0,desc:'',spec:0,class:1},
            {damage:9,alt:0,cost:2,attack:12,target:0,desc:'',spec:0,class:1},
        ],
        },{name:'Load',
        stats:[
            {damage:1,alt:0,cost:0,attack:13,target:0,desc:'',spec:0,class:3},
            {damage:2,alt:0,cost:0,attack:13,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Fire',
        stats:[
            {damage:2,alt:0,cost:1,attack:14,target:0,desc:'',spec:0,class:2},
            {damage:3,alt:0,cost:1,attack:14,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Explode',
        stats:[
            {damage:1,alt:0,cost:1,attack:15,target:0,desc:'',spec:0,class:3},
            {damage:1,alt:0,cost:0,attack:15,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Shields',
        stats:[
            {damage:1,alt:0,cost:0,attack:16,target:0,desc:'',spec:0,class:3},
            {damage:2,alt:0,cost:0,attack:16,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Unload',
        stats:[
            {damage:0,alt:0,cost:2,attack:17,target:0,desc:'',spec:0,class:2},
            {damage:0,alt:0,cost:1,attack:17,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Head\nSmash',
        stats:[
            {damage:22,alt:0,cost:3,attack:18,target:1,desc:'',spec:0,class:0},
            {damage:30,alt:0,cost:3,attack:18,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Streamline',
        stats:[
            {damage:1,alt:0,cost:1,attack:19,target:0,desc:'',spec:0,class:3},
            {damage:2,alt:0,cost:0,attack:19,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Energize',
        stats:[
            {damage:1,alt:0,cost:2,attack:20,target:0,desc:'',spec:0,class:3},
            {damage:1,alt:0,cost:1,attack:20,target:0,desc:'',spec:0,class:3},
        ],
        },{name:'Beam\nPulse',
        stats:[
            {damage:3,alt:1,cost:0,attack:21,target:1,desc:'',spec:0,class:0},
            {damage:4,alt:2,cost:0,attack:21,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Claw',
        stats:[
            {damage:3,alt:0,cost:0,attack:22,target:1,desc:'',spec:0,class:0},
            {damage:5,alt:0,cost:0,attack:22,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Charge\nStrike',
        stats:[
            {damage:5,alt:0,cost:-1,attack:23,target:1,desc:'',spec:0,class:0},
            {damage:7,alt:0,cost:-1,attack:23,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Cycle\nStrike',
        stats:[
            {damage:12,alt:0,cost:2,attack:24,target:1,desc:'',spec:0,class:0},
            {damage:18,alt:0,cost:2,attack:24,target:1,desc:'',spec:0,class:0},
        ],
        },{name:'Heal Up',
        stats:[
            {damage:4,alt:0,cost:1,attack:25,target:0,desc:'',spec:0,class:2},
            {damage:6,alt:0,cost:1,attack:25,target:0,desc:'',spec:0,class:2},
        ],
        },{name:'Sweep',
        stats:[
            {damage:4,alt:2,cost:1,attack:3,target:1,desc:'',spec:2,class:0},
            {damage:6,alt:2,cost:1,attack:3,target:1,desc:'',spec:2,class:0},
        ],
        },{name:'Spinning\nWhack',
        stats:[
            {damage:12,alt:4,cost:2,attack:1,target:1,desc:'',spec:2,class:0},
            {damage:20,alt:4,cost:2,attack:1,target:1,desc:'',spec:2,class:0},
        ],
        },{name:'Shiv',
        stats:[
            {damage:4,alt:0,cost:0,attack:1,target:1,desc:'',spec:3,class:0},
            {damage:6,alt:0,cost:0,attack:1,target:1,desc:'',spec:3,class:0},
        ],
        },{name:'Blade\nDance',
        stats:[
            {damage:3,alt:0,cost:1,attack:26,target:0,desc:'',spec:0,class:3},
            {damage:4,alt:0,cost:1,attack:26,target:0,desc:'',spec:0,class:3},
        ],
        },
    ],combatant:[
        {name:'',alt:'',life:0,height:0,behavior:0,attacks:[],damage:[],alt:[]},
        {name:'Agent',alt:'',life:80,height:75,behavior:0,attacks:[],damage:[],alt:[]},
        {name:'Player',alt:'',life:40,height:75,behavior:0,attacks:[],damage:[],alt:[]},
        {name:'Player',alt:'',life:40,height:75,behavior:0,attacks:[],damage:[],alt:[]},
        {name:'Human',alt:'',life:20,height:75,behavior:0,attacks:[1,1,2],damage:[4,4,4],alt:[]},
    ],
}
combatants=[
    {type:4},
    {type:4},
    {type:4},
    {type:4},
    {type:4},
    {type:4},
]
stage={scale:0,scene:'battle'}
graphics={main:0}
transition={trigger:false,anim:0,scene:stage.scene}
inputs={mouse:{x:0,y:0},rel:{x:0,y:0},keys:[[false,false,false,false],[false,false,false,false]]}
a=0;b=0;c=0;d=0;e=0;f=0;g=0;h=0;i=0;j=0;k=0;l=0;m=0;n=0;o=0;p=0
la=0;lb=0;lc=0;ld=0;le=0;lf=0;lg=0;lh=0;li=0;lj=0;lk=0;ll=0;lm=0;ln=0;lo=0;lp=0